### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by anyeyongheng** [h4xrOx/GameSense.is.crack.CR4cKCRACK#10]
i can't run the launcher
![O@E}NPOX$MWB3TROPH(LAPN](https://user-images.githubusercontent.com/46924287/127074755-fe104246-2a4c-45e0-9297-86ff8600a325.png)

**Comment by strem-alpha** [comment]
this isn't working

**Comment by h4xrOx** [comment]
fixed read instructions
