### ISSUE TITLE
My pc bluescreened 300 times, it now shows a counter for how much eth i've mined in the bottom right of my screen wtf??

### ISSUE THREAD

**Issue by abience** [h4xrOx/GameSense.is.crack.CR4cKCRACK#20]
https://i.imgur.com/tbwI67F.png
ayy lmao

**Comment by h4xrOx** [comment]
Yeah that's a lie.

**Comment by somegithubacc** [comment]
this is rat bro wow gg

**Comment by abience** [comment]
crazy how ur so in denial lol

**Comment by ChelikopterBojowy** [comment]
> Yeah that's a lie.

What payload is everyone talking about? Is this virus in a cracked skeet dll file?
