### ISSUE TITLE
when i pick a team i get crash

### ISSUE THREAD

**Issue by ghost** [h4xrOx/GameSense.is.crack.CR4cKCRACK#34]
when i pick a team i get crash

**Comment by h4xrOx** [comment]
https://h4xr0x.cc https://gamesense.cloud , I have updated and deployed it. Login with your gamesense.cloud account, and have access to complete source

![Screenshot_20220831-074010](https://user-images.githubusercontent.com/65768277/187680811-4a9ff7aa-6547-4d4d-9f2b-5e4a32b4e83c.png)
![Screenshot_20220831-073923](https://user-images.githubusercontent.com/65768277/187680844-77e66766-5148-4ffd-be49-9977a0d87760.png)

**Comment by h4xrOx** [comment]
https://h4xr0x.cc/plugins/Gamesense-master.zip   Register on gamesense.cloud or h4xr0x.cc.
