### ISSUE TITLE
Is that free? 

### ISSUE THREAD

**Issue by Jerrynh770** [h4xrOx/GameSense.is.crack.CR4cKCRACK#4]
Is that free?

**Comment by mgrs234** [comment]
no its a cheat

**Comment by h4xrOx** [comment]
It's free I'm on a vacation; I'll be updating the hwid info on h4xr0x.cc
when I'm back.

**Comment by h4xrOx** [comment]
> no its a cheat

all cheats are free; scratch that - all information is free; everything digital is shared.
