### ISSUE TITLE
the forum doesnt work

### ISSUE THREAD

**Issue by d0c-cpu** [h4xrOx/GameSense.is.crack.CR4cKCRACK#5]
MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '2851'' at line 1
Query:
SELECT COUNT(*) as 'unique' FROM mybbsg_ip_history WHERE IP='*�pA�Y � 9�k'' AND uid='2851'

am i banned????

**Comment by h4xrOx** [comment]
ahhh.. yeah where you have 2 ip. its nice of me to allow sql error messages. wait 30 minutes; or use another browser, vpn or clear cache + cookies.
