### ISSUE TITLE
forums broken

### ISSUE THREAD

**Issue by Xvvn** [h4xrOx/GameSense.is.crack.CR4cKCRACK#7]
SQL Error:
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '723'' at line 1
Query:
SELECT COUNT(*) as 'unique' FROM mybbsg_ip_history WHERE IP='&-���%hW����F'' AND uid='723'

I have tried a VPN/dif browser

**Comment by d0c-cpu** [comment]
you need to clear your cookies

**Comment by h4xrOx** [comment]
im updating the forum
